### PR TITLE
Send kPS2M_notifyKeyTime for palm rejection

### LINKED ISSUE #1228: [Feature Request] Ability to disable trackpad when pressing brightness keys (just like VoodooPS2)
Hi
In VoodooPS2, when typing the trackpad stops (disable temporarily), but in BrightnessKeys it doesn't, can you please implement this feature to BrightnessKeys?
Regards.

### PR DESCRIPTION
**Pull request by zhen-zen**
Close https://github.com/acidanthera/bugtracker/issues/1228

### CODE REVIEW

**Comment by seungjunProgramming** [comment]
@vit9696 @zhen-zen @usr-sse2 @al3xtjames @vandroiy2013 
Can you plz update this kext to support keyboard brightness(change brightness of keyboard backlight)???
(Natively in Big Sur)
(I have a keyboard brightness key that works, but doesn't show up at menu bar)

**Comment by zhen-zen** [comment]
Keyboard brightness implementations are usually vendor-specific. You may need drivers like [AsusSMC](https://github.com/hieplpvip/AsusSMC).

**Comment by AfterSchoolProgrammer** [comment]
Then how about power button fix patch???
Is it possible???

**Comment by zhen-zen** [comment]
I didn't get your point of power button fix and it's not appropriate to discuss unrelated issue in a PR.
This driver follows ACPI specs to implement brightness key handling which macOS doesn't support. However, there's an existing driver `AppleACPIButton` for power button and sleep button. If that one doesn't work, it could be either a broken ACPI implementation (if the button also won't work in linux) or flaw in methods (like premature `_INI` or `_STA`). And drivers could do nothing to fix it.

**Pull request merged**
