### PR TITLE
Update readme with special handling for ThinkPads

### PR DESCRIPTION
**Pull request by zhen-zen**
@Sniki Can you check it again?

### CODE REVIEW

**Comment by Sniki** [comment]
For some reasons ACPI patch method is not working, both newer and older iasl patch is not working.
A patchmatic extract shows no ACPI errors whatsoever.
A simple SSDT like this one works fine:

```
// Set NBCF = One to enable Brightness Control on older (Haswell) Thinkpad laptop models

DefinitionBlock ("", "SSDT", 2, "Sniki", "_NBCF", 0)
{
    External (NBCF, IntObj)

    If (_OSI ("Darwin"))
    {
        // Enable NBCF for Brightness Control
        NBCF = One
    }
}
```
Is it possible to be an OC patcher issue ?
Here are the logs:
[Bootlog.txt](https://github.com/acidanthera/BrightnessKeys/files/5470608/Bootlog.txt)
[grep - ACPI.txt](https://github.com/acidanthera/BrightnessKeys/files/5470609/grep.-.ACPI.txt)

CC @vit9696 @zhen-zen

**Comment by zhen-zen** [comment]
It seems like OC failed to patch ACPI table when the last byte is part of the `Find` data. Unfortunately, the `NBCF` definition locates exactly at the end of file through the last byte. I also did some patches on mine DSDT and it also failed when the last byte is involved.

```
02:122 00:005 OCA: Applying 6 byte ACPI patch skip 0, count 1
02:128 00:006 OCA: Patching DSDT of 198180 bytes with 0000000000000000 ID replaced 0 of 1
```

However, it sounds good in 
https://github.com/acidanthera/OpenCorePkg/blob/master/Library/OcMiscLib/DataPatcher.c#L21. Maybe I will print some logs here.

Update:
Sounds like just this line? Since 1 byte is already at `DataOff`, or we should still be able to patch 1 byte@0xff while the length is 0x100.
```
diff --git a/Library/OcMiscLib/DataPatcher.c b/Library/OcMiscLib/DataPatcher.c
index d7284b6a..d8837b77 100644
--- a/Library/OcMiscLib/DataPatcher.c
+++ b/Library/OcMiscLib/DataPatcher.c
@@ -36,7 +36,7 @@ FindPattern (
     return -1;
   }
 
-  while (DataOff + PatternSize < DataSize) {
+  while (DataOff + PatternSize <= DataSize) {
     Matches = TRUE;
     for (Index = 0; Index < PatternSize; ++Index) {
       if ((PatternMask == NULL && Data[DataOff + Index] != Pattern[Index])
```

https://github.com/acidanthera/OpenCorePkg/pull/148

**Comment by vit9696** [comment]
That was fixed thx to your patch. Can we merge the README update?

**Comment by zhen-zen** [comment]
Sure, please merge it.

**Pull request merged**
